age1=int(input("please enter your age"))
age2=int(input("please enter your age"))
age3=int(input("please enter your age"))
maxage=max(age1,age2,age3)
miniage=min(age1,age2,age3)
print("oldest age is",maxage)
print("youngest age is",miniage)